### ISSUE TITLE
Move from Glide to dep

### ISSUE THREAD

**Issue by richp10** [helloeave/dat#7]
Here is a start.. https://github.com/richp10/dat/blob/master/Gopkg.toml

Please note I handled the satori uuid reversion problem by importing older version - maybe handling it in revised code is better - up to you..

**Comment by bkono** [comment]
Since the vgo proposal has officially been accepted, it might be worth getting compatible with that instead. Having enjoyed and battled dep in the past, I'm good with either option. Currently exploring the usable patterns to integrate vgo in my other projects / apps moving forward, so I went ahead and started a [feature branch](https://github.com/helloeave/dat/compare/v2...bkono:feature/vgo) for it. Definitely a WIP. Happy to throw it away though if everyone else would prefer going the currently more stable route with dep.

@pascallouisperez What does helloeave use internally? Dep, vgo, something else?

**Comment by richp10** [comment]
I have not used vgo and have a certain amount of <sigh> at yet another phase of the go dependency debate.. but it does *seem* to be the future so happy either way.

**Comment by pascallouisperez** [comment]
As you say @bkono, if vgo is what's going to be supported by going forward, then conforming to that earlier is likely better. Given your attempt at using it, is it easy for others (not using vgo yet), to incorporate the package?

@richp10 We fixed the library to use the latest satori uuid package here https://github.com/helloeave/dat/commit/79dab782cafa342bd7451c21327f84c0fae60d1c

Internally, we've been using github.com/kardianos/govendor for dependency management.

**Comment by bkono** [comment]
@pascallouisperez My experience so far indicates the answer is ... yes and no. Up until the point a package makes use of the module versioning import strategy that vgo enables, it is very easy. The general approach of vgo encouraging a tip branch + vtagged or branched versions makes it play well with all the other package managers I've tested (majority of compatibility experience is with dep, as thats what I've been using in projects for quite awhile). Its that special sauce for creating smoother breaking changes and allowing a package to reference a different version of itself via a go.mod change to the module import path that makes it step away from the comfort zone of the other package managers. While its a super useful feature, I think avoiding it for the near term while other package managers figure out how/whether they will deal with that would keep the package more readily usable.
